version: 2

release:
  draft: true

builds:
  - builder: rust
    id: cross
    binary: check-updates
    command: zigbuild
    flags:
      - --release
      - -p=check-updates-cli
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-pc-windows-gnu
      - aarch64-unknown-linux-gnu

  - builder: rust
    id: macos
    binary: check-updates
    command: build
    flags:
      - --release
      - -p=check-updates-cli
    targets:
      - aarch64-apple-darwin

changelog:
  disable: true

archives:
  - formats: [tar.xz]
    name_template: >-
      {{ .ProjectName }}-{{ .Arch }}-{{ .Os }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt
